version: 2.1
orbs:
    aws-cli: circleci/aws-cli@0.1.16
jobs:
  my-job:
        docker:
          - image: circleci/node:latest
        steps:
        - checkout
        - run:
            name: "Test the image..."
            command: |
                npm run coverage
workflows:
  my-job-workflow:
    jobs:
      - my-job
