version: 2.1
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Test coverage"
          command: npm run coverage
workflows:
  my-job-workflow:
    jobs:
      - my-job
