version: 2.1
orbs:
    aws-cli: circleci/aws-cli@0.1.16
jobs:
  my-job:
        executor: aws-cli/default
        steps:
        - aws-cli/setup:
            profile-name: default
        - setup_remote_docker:
            version: "20.10.7"
            docker_layer_caching: true
        - checkout
        - run:
            name: "Test the image..."
            command: |
                npm run coverage
workflows:
  my-job-workflow:
    jobs:
      - my-job
